:wrench: s コマンド追加など

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -66,7 +66,6 @@ alias mkdir='mkdir -p'
 alias p='pushd'
 alias diff='diff -U1'
 alias exsh='exec $SHELL -l'
-alias s='git status'
 alias a='git add . && git status'
 alias ga='g a'
 alias r='git reset && git status'
@@ -105,6 +104,32 @@ alias v='(){vim $(gitdiffls $1)}'
 gs() {
   #git diff master HEAD --name-only
   git status
+}
+
+#サブモジュールごとに実行する
+s() {
+  (
+    CURRENT_DIR=$(pwd)
+    function catch {
+      # 失敗したらカレントディレクトリへ
+      cd $CURRENT_DIR
+    }
+    trap catch ERR
+
+    if [ -z "$1" ]; then
+        echo "Missing Command" >&2
+        return
+    fi
+
+    IFS=$'\n'
+    for DIR in $(git submodule foreach -q sh -c pwd); do
+      (
+        echo "[[$DIR]]>>"
+        cd "$DIR" && "$@"
+      ) &
+    done
+    wait
+  )
 }
 
 dr() {
